python -m main --config_file='./qaoa.yaml' TRAIN.OPTIMIZER_NAME adam DATA.PROBLEM_TYPE vqls DATA.VECTOR_CHOICE alternation TRAIN.APPLY_SR False DATA.NUM_SITES 2 TRAIN.BATCH_SIZE 128 TRAIN.NUM_EPOCHS 6000 TRAIN.LEARNING_RATE 0.00025 DATA.NUM_CHAINS 8 MODEL.MODEL_NAME rbm_c

python -m main --config_file='./qaoa.yaml' TRAIN.OPTIMIZER_NAME adam DATA.PROBLEM_TYPE vqls DATA.VECTOR_CHOICE alternation TRAIN.APPLY_SR False DATA.NUM_SITES 3 TRAIN.BATCH_SIZE 128 TRAIN.NUM_EPOCHS 6000 TRAIN.LEARNING_RATE 0.00025 DATA.NUM_CHAINS 8 MODEL.MODEL_NAME rbm_c

python -m main --config_file='./qaoa.yaml' TRAIN.OPTIMIZER_NAME adam DATA.PROBLEM_TYPE vqls DATA.VECTOR_CHOICE alternation TRAIN.APPLY_SR False DATA.NUM_SITES 4 TRAIN.BATCH_SIZE 128 TRAIN.NUM_EPOCHS 6000 TRAIN.LEARNING_RATE 0.00025 DATA.NUM_CHAINS 8 MODEL.MODEL_NAME rbm_c

python -m main --config_file='./qaoa.yaml' TRAIN.OPTIMIZER_NAME adam DATA.PROBLEM_TYPE vqls DATA.VECTOR_CHOICE alternation TRAIN.APPLY_SR False DATA.NUM_SITES 5 TRAIN.BATCH_SIZE 128 TRAIN.NUM_EPOCHS 6000 TRAIN.LEARNING_RATE 0.00025 DATA.NUM_CHAINS 8 MODEL.MODEL_NAME rbm_c

python -m main --config_file='./qaoa.yaml' TRAIN.OPTIMIZER_NAME adam DATA.PROBLEM_TYPE vqls DATA.VECTOR_CHOICE alternation TRAIN.APPLY_SR False DATA.NUM_SITES 6 TRAIN.BATCH_SIZE 128 TRAIN.NUM_EPOCHS 6000 TRAIN.LEARNING_RATE 0.00025 DATA.NUM_CHAINS 8 MODEL.MODEL_NAME rbm_c

python -m main --config_file='./qaoa.yaml' TRAIN.OPTIMIZER_NAME adam DATA.PROBLEM_TYPE vqls DATA.VECTOR_CHOICE alternation TRAIN.APPLY_SR False DATA.NUM_SITES 7 TRAIN.BATCH_SIZE 128 TRAIN.NUM_EPOCHS 6000 TRAIN.LEARNING_RATE 0.00025 DATA.NUM_CHAINS 8 MODEL.MODEL_NAME rbm_c

python -m main --config_file='./qaoa.yaml' TRAIN.OPTIMIZER_NAME adam DATA.PROBLEM_TYPE vqls DATA.VECTOR_CHOICE alternation TRAIN.APPLY_SR False DATA.NUM_SITES 8 TRAIN.BATCH_SIZE 128 TRAIN.NUM_EPOCHS 6000 TRAIN.LEARNING_RATE 0.00025 DATA.NUM_CHAINS 8 MODEL.MODEL_NAME rbm_c

python -m main --config_file='./qaoa.yaml' TRAIN.OPTIMIZER_NAME adam DATA.PROBLEM_TYPE vqls DATA.VECTOR_CHOICE alternation TRAIN.APPLY_SR False DATA.NUM_SITES 9 TRAIN.BATCH_SIZE 128 TRAIN.NUM_EPOCHS 6000 TRAIN.LEARNING_RATE 0.00025 DATA.NUM_CHAINS 8 MODEL.MODEL_NAME rbm_c

python -m main --config_file='./qaoa.yaml' TRAIN.OPTIMIZER_NAME adam DATA.PROBLEM_TYPE vqls DATA.VECTOR_CHOICE alternation TRAIN.APPLY_SR False DATA.NUM_SITES 10 TRAIN.BATCH_SIZE 128 TRAIN.NUM_EPOCHS 6000 TRAIN.LEARNING_RATE 0.00025 DATA.NUM_CHAINS 8 MODEL.MODEL_NAME rbm_c

python -m main --config_file='./qaoa.yaml' TRAIN.OPTIMIZER_NAME adam DATA.PROBLEM_TYPE vqls DATA.VECTOR_CHOICE alternation TRAIN.APPLY_SR False DATA.NUM_SITES 11 TRAIN.BATCH_SIZE 128 TRAIN.NUM_EPOCHS 6000 TRAIN.LEARNING_RATE 0.00025 DATA.NUM_CHAINS 8 MODEL.MODEL_NAME rbm_c

python -m main --config_file='./qaoa.yaml' TRAIN.OPTIMIZER_NAME adam DATA.PROBLEM_TYPE vqls DATA.VECTOR_CHOICE alternation TRAIN.APPLY_SR False DATA.NUM_SITES 12 TRAIN.BATCH_SIZE 128 TRAIN.NUM_EPOCHS 6000 TRAIN.LEARNING_RATE 0.00025 DATA.NUM_CHAINS 8 MODEL.MODEL_NAME rbm_c